# Generated by Django 5.2.16 on 2026-09-26 14:42

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("paperless", "0018_applicationconfiguration_barcode_store_values"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationconfiguration",
            name="barcode_enable_links",
            field=models.BooleanField(
                null=True,
                verbose_name="Enables clickable links for URL barcodes",
            ),
        ),
    ]
