# Generated by Django 5.2.16 on 2026-09-26 14:42

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0027_documentbarcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentbarcode",
            name="rect",
            field=models.JSONField(
                blank=True,
                help_text="Rectangle [x0, y0, x1, y1] in PDF coordinates of the page as shown, i.e. in the archive file if there is one",
                null=True,
                verbose_name="position",
            ),
        ),
    ]
